/* Generated By:JavaCC: Do not edit this line. NumeralConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NumeralConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 1;
  /** RegularExpression Id. */
  int SUBTRACT = 2;
  /** RegularExpression Id. */
  int DIVIDE = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int NUMERAL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "<NUMERAL>",
  };

}
